[options]
admin_passwd = admin
proxy_mode = True
without_demo = True
list_db = False

addons_path = ./addons

db_host = False
db_port = False
db_user = odoo
db_password = False

logfile = odoo.log

max_cron_threads = 2
db_maxconn = 64
