[options]
db_user = openpg
db_password = admin
db_name = synergy_sys_company
db_host = localhost
db_port = 5432
db_maxconn = 20
db_sslmode = prefer

addons_path = E:/Odoo/odoo-18.0/addons,E:/Odoo/odoo-18.0/custom_addons
data_dir = E:/Odoo/data_fast
logfile = E:/Odoo/odoo-18.0/odoo-production.log

admin_passwd = moner123osamah
list_db = False
proxy_mode = True
block_external_requests = False

disable_enterprise_checks = True
validate_license = False
license_server = False
publisher_warranty_url = False
enable_enterprise_ripple_effect = False

log_level = warn

workers = 8
max_cron_threads = 2
limit_memory_soft = 8GB
limit_memory_hard = 12GB   
limit_request = 2048
limit_time_cpu = 300
limit_time_real = 600
limit_time_real_cron = 600

transient_age_limit = 5  
transient_count_limit = 50  
reportgz = False
without_demo = True

wkhtmltopdf_path = C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe

http_interface = 0.0.0.0
http_port = 8069
longpolling_port = 8072

max_file_upload_size = 5242880
secure_certificate = False

session_storage_ttl = 7200  
db_template = template0